import 'controller/cancel_booking_controller.dart';import 'package:flutter/material.dart';import 'package:xomfort/core/app_export.dart';import 'package:xomfort/widgets/custom_button.dart';
// ignore_for_file: must_be_immutable
class CancelBookingBottomsheet extends StatelessWidget {CancelBookingBottomsheet(this.controller);

CancelBookingController controller;

@override Widget build(BuildContext context) { return SingleChildScrollView(child: Container(width: double.infinity, decoration: AppDecoration.outlineGray8002.copyWith(borderRadius: BorderRadiusStyle.customBorderTL40), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.center, mainAxisAlignment: MainAxisAlignment.start, children: [Container(height: getVerticalSize(3.00), width: getHorizontalSize(38.00), margin: getMargin(left: 24, top: 8, right: 24), decoration: BoxDecoration(color: ColorConstant.gray700, borderRadius: BorderRadius.circular(getHorizontalSize(1.50)))), Padding(padding: getPadding(left: 24, top: 29, right: 24), child: Text("lbl_cancel_booking".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtUrbanistRomanBold24RedA200)), Container(width: getHorizontalSize(338.00), margin: getMargin(left: 24, top: 34, right: 24), child: Text("msg_are_you_sure_yo2".tr, maxLines: null, textAlign: TextAlign.center, style: AppStyle.txtUrbanistRomanBold20)), Container(width: getHorizontalSize(370.00), margin: getMargin(left: 24, top: 16, right: 24), child: Text("msg_only_80_of_the".tr, maxLines: null, textAlign: TextAlign.center, style: AppStyle.txtUrbanistRegular14WhiteA700.copyWith(letterSpacing: 0.20))), Container(margin: getMargin(left: 24, top: 24, right: 24, bottom: 66), decoration: BoxDecoration(borderRadius: BorderRadius.circular(getHorizontalSize(29.00))), child: Row(mainAxisAlignment: MainAxisAlignment.start, crossAxisAlignment: CrossAxisAlignment.center, mainAxisSize: MainAxisSize.max, children: [CustomButton(width: 184, text: "lbl_cancel".tr, variant: ButtonVariant.FillGray800, onTap: onTapCancel), CustomButton(width: 184, text: "lbl_continue".tr, margin: getMargin(left: 12))]))]))); } 
onTapCancel() { Get.back(); } 
 }
